path:
  ckpt_path: "./output/ckpt/mupev"
  log_path: "./output/log/mupev"
  result_path: "./output/result/mupev"
optimizer:
  batch_size: 16 
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 400
  anneal_steps: [30000, 50000, 100000, 250000]
  anneal_rate: 0.3
step:
  total_step: 500000
  log_step: 500
  synth_step: 1000
  val_step: 5000
  save_step: 10000
